language: android
jdk: oraclejdk8
env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=16
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    -
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3
    # - build-tools-26.0.1

    # ANDROID_BUILD_TOOLS=28.0.3
    # The SDK version used to compile your project
    - android-28
    - extra
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    # - sys-img-x86-android-26
    # - sys-img-x86-google_apis_playstore-26
    - sys-img-armeabi-v7a-google_apis-26
  before_install:
    - yes | sdkmanager "platforms;android-28;default;armeabi-v7a"
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
git:
  depth: 3

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-26 --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list targets
  - ./gradlew clean build -PdisablePreDex connectedAndroidTest --stacktrace

